### ISSUE TITLE
Paginating a large collection of images MediaList?

### ISSUE THREAD

**Issue by patforg** [humanmade/asset-manager-framework#21]
Hi I'm implementing AMF to get media from an API that has a large collection with thousands of images.  I don't want to populate all the items in the returned MediaList but would rather use pagination.  Is there a way with the current MediaList class to paginate results?

**Comment by patforg** [comment]
Also just noticed that MediaList is a final class, so it's not possible to extend it.  My plan was to extend it and make a version that uses an iterator that implements the pagination.

I would suggest to add a MediaListInterface and we could make BynderAssetProvider::request() return an object that implements that interface rather than an instance of MediaList.

**Comment by johnbillion** [comment]
Yes your provider should only return the correct number of results as requested by `$args['posts_per_page']` and `$args['paged']`. [Here's an example from the Unsplash provider](https://github.com/humanmade/amf-unsplash/blob/d0965f551338fcddef60c26ee51ceb957392beb4/inc/class-provider.php#L22-L51).

Related: #4.

**Comment by patforg** [comment]
Yeah I manage to get it working late last night.  I misunderstood the role of media list and that pagination would work if I simply return the right amount of items.

Thanks for the reply!
