### ISSUE TITLE
Throw an exception if the provider returns more results than expected

### ISSUE THREAD

**Issue by johnbillion** [humanmade/asset-manager-framework#4]
As observed by @rmccue, if the media library attachments query returns _more_ results than expected then it breaks the pagination.

AMF should throw an exception if the provider returns more than the requested `posts_per_page` number of media items.

**Comment by rmccue** [comment]
I'm experiencing some other spooky action here as well, which I haven't entirely tracked down, so this could be caused by something else. In any case, seems there's some sort of hidden assumption I'm hitting. In any case, docs around this would be useful.
