### ISSUE TITLE
Image detail page causes error when used with Smart Media

### ISSUE THREAD

**Issue by rmccue** [humanmade/asset-manager-framework#5]
When using the [Smart Media plugin](https://github.com/humanmade/smart-media), the page crashes when opening the details view, with the following error:

<img width="735" alt="data.model.get(...) is undefined" src="https://user-images.githubusercontent.com/21655/79585407-a8f99e80-80c7-11ea-842f-92029eefdac8.png">

This is likely an issue with Smart Media, but possible that other plugins could cause similar errors.

**Comment by rmccue** [comment]
Looks like this is crashing from `data.model.get('editor').can.rotate`; Smart Media expects to set the `editor` field on the `wp_prepare_attachment_for_js` filter, which is seems is not called.

Should AMF set that field, or should Smart Media expect it to not be set? Not sure.

**Comment by rmccue** [comment]
From some further tests, it seems like most callbacks fail if there's no actual attachment object, so I think it's probably OK for AMF to not call that filter. Leaving open in case anyone disagrees though.

**Comment by johnbillion** [comment]
Yeah as you noted the `wp_prepare_attachment_for_js` filter in WordPress core expects there to be a corresponding `WP_Post` object which represents the attachment, which is not the case when AMF is in use. If this filter is essential, we could spoof one or provide a dummy one, but that starts taking us down the path of lying about attachments which I want to avoid.

I think this is a wontfix, but this filter should be mentioned in the AMF documentation as an item that needs to be checked if it's in use, for example check that sufficient error handling is in place if the attachments in the model don't contain the expected properties.

**Comment by johnbillion** [comment]
Going to close this in favour of https://github.com/humanmade/smart-media/issues/50
